FROM openjdk:11-jdk

COPY . /app

WORKDIR /app

RUN chmod +x gradlew
RUN ./gradlew build -x test

RUN mkdir -p /app/backend
ARG JAR_FILE=build/libs/db_project-0.0.1-SNAPSHOT.jar
RUN cp /app/${JAR_FILE} /app/backend/app.jar

EXPOSE 8080

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
ENTRYPOINT ["./wait-for-it.sh", "mysql:3306", "-s", "-t", "100", "--"]